language: node_js
node_js:
- '8'
- '9'
- '10'
before_install:
- npm install -g grunt-cli
notifications:
  slack:
    secure: GZK9+yonwm5yuw0cq6V2DS1xNPYzij1znoQ9mlFyofjrhymqNRCI6kN34tkRgo2PW4H92DfL42BMlpjN0aKqilKi69L+k03eSL7tl2Dl/cyPbScNY0TtBuqnCLJPUiDsrVlwZM3OehS2rF/5+PamL9QvDOw2jzciSzWJi5eoHU+1OtUa2xc/d//r4uZc0rE1o9w9exWfl4AHwYcg015EY6Whf6nOuV2VG5aYTGsKVc9jctn33eDGiTjNvpTDmNkN3tlp49W1OVbulN6PCIP06ky/byzXFzZbdayBoZzQG7wdA1jxQgtCsoQiD88WJu6+6HrHhnLIrJ/nnltDXfnMSb0ZQzMc5nbYvC+/eRjwwT7Vz6fGOKOOrnCXalh0UaHlvQtJvH+VvHyvjoFoLRPZd5fZAUzmBI+FRjTYUh8D3MOAy6oZqAkYDIHX3WQOg0V/M5hG1EyC3PNvs41V+leHi1C4TmLoj9x2QXmcKaC7PuO+AHRRk4RvnmL0m6CGG2KO8g4IMKfwCv3nZOvCIJleWcvyf5x2U+n4Xaix9TZUH6dciAnSOQT6Bcg3Ai8CgkbDsifrYwlplVgi/W0h/vVxHO472wPBYBgan2xPusxiIBKXn7iccy6zh/WYq0DYQLFq8KI6irBCzMCsOp7iwxHclCjdAfEQPuKzWnPZNqAJ8H4=
